version: 2

references:
  container_config: &container_config
    working_directory: ~/repo
    docker:
      - image: circleci/node:8

  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Npm v$(npm -v)"
      - run:
          name: Install dependencies
          working_directory: src
          command: npm install --no-progress
      - run:
          name: Test
          working_directory: src
          command: npm test -- --coverage
      - store_artifacts:
          path: src/coverage
          destination: coverage
      - run:
          name: Execute deploy command
          command: |
            echo ${CIRCLE_BRANCH}
          filters:
            branches:
              only: master
