version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Npm v$(npm -v)"
      - run:
          name: Install dependencies
          working_directory: src
          command: npm install --no-progress
      - run:
          name: Test
          working_directory: src
          command: npm test
